### ISSUE TITLE
Project pages

### ISSUE THREAD

**Issue by khvorov45** [khvorov45/opendatacapture#42]
Each project should have its own page which provides:

- [x] Ability to create new tables #69
- [x] Ability to view existing table structure #69 
- [x] Ability to remove existing tables #69 
- [x] Ability to enter table data #78 
- [x] Ability to view existing table data #78 
- [x] Ability to remove table data #78

**Comment by khvorov45** [comment]
Close this one. Open new ones for additions to project pages.
