### ISSUE TITLE
Project manipulation API

### ISSUE THREAD

**Issue by khvorov45** [khvorov45/opendatacapture#43]
There needs to be project-level API for:

- [x] Creating tables #44

- [x] Dropping tables #44

- [x] Getting a list of table names #46 

- [x] Getting one table's metadata #45

- [x] Getting all tables metadata #66

- [x] Inserting table data #51 

- [x] Removing all table data #52

- [x] Getting one table's table data #51

**Comment by khvorov45** [comment]
Closing this for now. Open another for more project-API related additions.
